# Generated by Django 5.0.4 on 2024-06-23 11:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('sneaker_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sneaker_brand', models.CharField(max_length=100)),
                ('sneaker_name', models.CharField(max_length=100)),
                ('sneaker_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sneaker_inventory', models.IntegerField()),
                ('sneaker_img', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_password', models.CharField(max_length=100)),
                ('customer_dob', models.DateField()),
                ('customer_phone', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_payment_method', models.CharField(max_length=4)),
                ('tng_details', models.CharField(max_length=100, null=True)),
                ('card_number', models.CharField(max_length=100, null=True)),
                ('expiry_date', models.CharField(max_length=5, null=True)),
                ('cvv', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('order_placed_date', models.DateTimeField(auto_now_add=True)),
                ('order_payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_size', models.IntegerField()),
                ('sneaker_quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.order')),
                ('sneaker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.sneaker')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_size', models.IntegerField()),
                ('sneaker_quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cart')),
                ('sneaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.sneaker')),
            ],
        ),
        migrations.CreateModel(
            name='Sneaker_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(16)])),
                ('sneaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.sneaker')),
            ],
        ),
    ]
