# Generated by Django 5.0.4 on 2024-05-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_cart_total_price_cart_cart_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='sneaker_size',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tng_details',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='sneaker_size',
        ),
    ]
