# Generated by Django 5.0.4 on 2024-05-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_cart_item_sneaker_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='sneaker_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='card_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='expiry_date',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tng_details',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_item',
            name='sneaker_size',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
