# Generated by Django 5.0.4 on 2024-05-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_cart_item_sneaker_size_customer_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tng_details',
        ),
    ]
