# Generated by Django 5.0.4 on 2024-05-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_remove_customer_card_number_remove_customer_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='card_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='expiry_date',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tng_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
