# Generated by Django 5.0.4 on 2024-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_customer_card_number_customer_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
