# Generated by Django 5.0.4 on 2024-05-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_order_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='sneaker_url',
        ),
        migrations.AddField(
            model_name='sneaker',
            name='sneaker_img',
            field=models.BinaryField(default=0, max_length='max'),
            preserve_default=False,
        ),
    ]
